name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Remove existing pnpm
        run: |
          npm uninstall -g pnpm || true
          rm -rf ~/.pnpm*

      - name: Install pnpm 8
        run: npm install -g pnpm@8.20.0

      - name: Check pnpm version
        run: pnpm --version

      - name: Install deps
        working-directory: ./plugins/template
        run: pnpm install

      - name: Build plugin
        working-directory: ./plugins/template
        run: pnpm run build

      - name: Copy files
        run: |
          cp README.md dist/README.md
          printf -- "---\npermalink: /404.html\n---\n" > dist/404.md
          printf -- "> **Note:** link goes here\n\n" >> dist/404.md
          cat README.md >> dist/404.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true
